def get_manual_hackathons():
    """
    Manually curated hackathons - Updated regularly
    These are verified hackathons friendly for CSE freshers
    """
    return [
        {
            'name': 'Smart India Hackathon 2025',
            'platform': 'Other',
            'organizer': 'Government of India',
            'mode': 'Hybrid',
            'registration_link': 'https://www.sih.gov.in/',
            'prize_pool': '₹1,00,000 per winning team',
            'fresher_friendly': True,
            'status': 'Upcoming',
        },
        {
            'name': 'Google Solution Challenge 2025',
            'platform': 'Other',
            'organizer': 'Google Developer Student Clubs',
            'mode': 'Online',
            'registration_link': 'https://developers.google.com/community/gdsc-solution-challenge',
            'prize_pool': '$3,000 + Mentorship',
            'fresher_friendly': True,
            'status': 'Live',
        },
        {
            'name': 'Microsoft Imagine Cup 2025',
            'platform': 'Other',
            'organizer': 'Microsoft',
            'mode': 'Online',
            'registration_link': 'https://imaginecup.microsoft.com/',
            'prize_pool': '$100,000',
            'fresher_friendly': True,
            'status': 'Live',
        },
        {
            'name': 'HackMIT 2025',
            'platform': 'MLH',
            'organizer': 'MIT',
            'mode': 'Hybrid',
            'registration_link': 'https://hackmit.org/',
            'fresher_friendly': True,
            'status': 'Upcoming',
        },
        {
            'name': 'ETHIndia 2025',
            'platform': 'Devfolio',
            'organizer': 'ETHIndia',
            'mode': 'Hybrid',
            'registration_link': 'https://ethindia.co/',
            'prize_pool': '$50,000+',
            'fresher_friendly': True,
            'status': 'Upcoming',
        },
        {
            'name': 'HackBengaluru',
            'platform': 'Devfolio',
            'organizer': 'Community Driven',
            'mode': 'Offline',
            'registration_link': 'https://hackbengaluru.tech/',
            'fresher_friendly': True,
            'status': 'Upcoming',
        },
        {
            'name': 'TreeHacks (Stanford)',
            'platform': 'MLH',
            'organizer': 'Stanford University',
            'mode': 'Hybrid',
            'registration_link': 'https://www.treehacks.com/',
            'fresher_friendly': True,
            'status': 'Upcoming',
        },
        {
            'name': 'AWS DeepRacer Student League',
            'platform': 'Other',
            'organizer': 'Amazon Web Services',
            'mode': 'Online',
            'registration_link': 'https://aws.amazon.com/deepracer/student/',
            'prize_pool': 'Scholarships + AWS Credits',
            'fresher_friendly': True,
            'status': 'Live',
        },
        {
            'name': 'HackNITR',
            'platform': 'Devfolio',
            'organizer': 'NIT Rourkela',
            'mode': 'Hybrid',
            'registration_link': 'https://hacknitr.com/',
            'fresher_friendly': True,
            'status': 'Upcoming',
        },
        {
            'name': 'Hack36',
            'platform': 'Devfolio',
            'organizer': 'MNNIT Allahabad',
            'mode': 'Hybrid',
            'registration_link': 'https://hack36.com/',
            'fresher_friendly': True,
            'status': 'Upcoming',
        }
    ]